<div class="loading-page" style="position: fixed;
    z-index: 9999;
    width: 100%;
    height: 100vh;
    background: white;
    display: flex;
    justify-content: center;
    align-items: center;">
    <div class="loadingio-spinner-double-ring-4gsm5nocbcu"><div class="ldio-0kg0wkind5y">
<div></div>
<div></div>
<div><div></div></div>
<div><div></div></div>
</div></div>
<style type="text/css">
@keyframes ldio-0kg0wkind5y {
  0% { transform: rotate(0) }
  100% { transform: rotate(360deg) }
}
.ldio-0kg0wkind5y div { box-sizing: border-box!important }
.ldio-0kg0wkind5y > div {
  position: absolute;
  width: 144px;
  height: 144px;
  top: 28px;
  left: 28px;
  border-radius: 50%;
  border: 16px solid #000;
  border-color: #53378b transparent #53378b transparent;
  animation: ldio-0kg0wkind5y 1s linear infinite;
}

.ldio-0kg0wkind5y > div:nth-child(2), .ldio-0kg0wkind5y > div:nth-child(4) {
  width: 108px;
  height: 108px;
  top: 46px;
  left: 46px;
  animation: ldio-0kg0wkind5y 1s linear infinite reverse;
}
.ldio-0kg0wkind5y > div:nth-child(2) {
  border-color: transparent #172948 transparent #172948
}
.ldio-0kg0wkind5y > div:nth-child(3) { border-color: transparent }
.ldio-0kg0wkind5y > div:nth-child(3) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-0kg0wkind5y > div:nth-child(3) div:before, .ldio-0kg0wkind5y > div:nth-child(3) div:after { 
  content: "";
  display: block;
  position: absolute;
  width: 16px;
  height: 16px;
  top: -16px;
  left: 48px;
  background: #53378b;
  border-radius: 50%;
  box-shadow: 0 128px 0 0 #53378b;
}
.ldio-0kg0wkind5y > div:nth-child(3) div:after {
  left: -16px;
  top: 48px;
  box-shadow: 128px 0 0 0 #53378b;
}

.ldio-0kg0wkind5y > div:nth-child(4) { border-color: transparent; }
.ldio-0kg0wkind5y > div:nth-child(4) div {
  position: absolute;
  width: 100%;
  height: 100%;
  transform: rotate(45deg);
}
.ldio-0kg0wkind5y > div:nth-child(4) div:before, .ldio-0kg0wkind5y > div:nth-child(4) div:after {
  content: "";
  display: block;
  position: absolute;
  width: 16px;
  height: 16px;
  top: -16px;
  left: 30px;
  background: #172948;
  border-radius: 50%;
  box-shadow: 0 92px 0 0 #172948;
}
.ldio-0kg0wkind5y > div:nth-child(4) div:after {
  left: -16px;
  top: 30px;
  box-shadow: 92px 0 0 0 #172948;
}
.loadingio-spinner-double-ring-4gsm5nocbcu {
  width: 200px;
  height: 200px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}
.ldio-0kg0wkind5y {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-0kg0wkind5y div { box-sizing: content-box; }
/* generated by https://loading.io/ */
</style>

</div>
